version: '2'
services:
  amr-console:
    image: "amr"
    user: cranacho
    working_dir: /home/cranacho/amrdb
    volumes: 
     - ./amrdb:/home/cranacho/amrdb
     - ./notebook:/home/cranacho/notebook
    environment:
     - PYTHONPATH=/home/cranacho/amrdb
     - CONNECTION_STRING=${AMR_CONNECTION_STRING}
     - LC_ALL=C.UTF-8
     - LANG=C.UTF-8

    stdin_open: true
    tty: true
    container_name: amr-container
    ports:
        - 5030:8081
    command: jupyter notebook --notebook-dir=../notebook

