version: '2'
services:
  amr-console:
    image: "amr"
    user: amr
    working_dir: /home/amr/amrdb
    volumes: 
     - ./amrdb:/home/amr/amrdb
    environment:
     - PYTHONPATH=/home/amr/amrdb
     - CONNECTION_STRING=postgresql+psycopg2://amr:monitor-me@amr-postgres:5432/amr
     - RTL_TCP_HOST_PORT=1234
     - LC_ALL=C.UTF-8
     - LANG=C.UTF-8
    stdin_open: true
    tty: true
    container_name: amr-container

  amr-postgres:
    image: postgres:latest
    volumes: 
      - amr-postgres:/var/lib/postgresql/data

volumes:
  amr-postgres:
    external: true
