version: '2'
services:
  amr-console:
    image: "amr"
    user: cranacho
    working_dir: /home/cranacho/amrdb
    volumes: 
     - ./amrdb:/home/cranacho/amrdb
    environment:
     - PYTHONPATH=/home/cranacho/amrdb
     - CONNECTION_STRING=postgresql+psycopg2://cranacho:${AMRDB_PASSWORD}@amr-postgres:5432/amr
     - LC_ALL=C.UTF-8
     - LANG=C.UTF-8
    stdin_open: true
    tty: true
    container_name: amr-container
    ports:
     - 5022:8081

  amr-postgres:
    image: postgres:latest
    volumes: 
      - amr-postgres:/var/lib/postgresql/data

volumes:
  amr-postgres:
    external: true
